-- 新增 CIRCULATION_HISTORY.DISPOSE_NOTE：工程师处置时的工程备注文本
-- DISPOSE_DETAIL 仅存放规则化处置详情（如 DG: / RT:）及其他非工程备注文本

ALTER TABLE "FT_OWEN"."CIRCULATION_HISTORY" ADD ("DISPOSE_NOTE" VARCHAR2(1024));

COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY.DISPOSE_NOTE IS '工程师处置工程备注（最长1024）';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY.DISPOSE_DETAIL IS '规则化处置详情（如 DG:/RT:）及其他非工程备注文本（最长1024）';
