-- 扩容 CIRCULATION_HISTORY.DISPOSE_DETAIL，以容纳降级/重测结构化详情
ALTER TABLE "FT_OWEN"."CIRCULATION_HISTORY" MODIFY ("DISPOSE_DETAIL" VARCHAR2(1024));

COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY.DISPOSE_DETAIL IS '操作备注/处置详情（最长1024）';
