-- FT_OWEN.CIRCULATION_HISTORY 定义

CREATE TABLE "FT_OWEN"."CIRCULATION_HISTORY" 
   (	"ID" NUMBER(38,0) DEFAULT FT_OWEN.SEQ_CIRCULATION.nextval, 
	"HOLD_RECORD_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"DISPOSED_OWNER_ID" NUMBER(38,0) DEFAULT 1 NOT NULL ENABLE, 
	"DISPOSE" NUMBER(38,0) DEFAULT 0, 
	"NEXT_OWNER_ID" NUMBER(38,0), 
	"DISPOSE_SOURCE" VARCHAR2(100), 
	"DISPOSE_DTTM" DATE, 
	"DISPOSE_TYPE" NUMBER(38,0), 
	"DISPOSE_DETAIL" VARCHAR2(1024), 
	"DISPOSE_NOTE" VARCHAR2(1024), 
	"DISPOSE_MANUAL_NOTE" VARCHAR2(1024), 
	 CONSTRAINT "PK_CIRCULATION_HISTORY" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FT_OWEN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FT_OWEN" ;

COMMENT ON TABLE FT_OWEN.CIRCULATION_HISTORY IS '处置单流转记录';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY.DISPOSED_OWNER_ID IS '默认1(root)代表是系统生成';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY.DISPOSE_SOURCE IS '处置信息来源, SYS or JDY';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY.DISPOSE_TYPE IS '创建、放行、降级、重测、可靠性分析、关闭、转交、回退';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY.DISPOSE_DETAIL IS '操作备注';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY.DISPOSE_NOTE IS '工程备注';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY.DISPOSE_MANUAL_NOTE IS '手输备注（工程师/生产任意处置可选，最长1024）';


-- FT_OWEN.CIRCULATION_HISTORY 外键

ALTER TABLE "FT_OWEN"."CIRCULATION_HISTORY" ADD CONSTRAINT "CIRCULATION_HISTORY_FT_HOLD_RECORD_FK" FOREIGN KEY ("HOLD_RECORD_ID")
	  REFERENCES "FT_OWEN"."FT_HOLD_RECORD" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FT_OWEN"."CIRCULATION_HISTORY" ADD CONSTRAINT "CIRCULATION_HISTORY_USERS_FK" FOREIGN KEY ("DISPOSED_OWNER_ID")
	  REFERENCES "FT_OWEN"."USERS" ("ID") ENABLE;