-- 扩容 CIRCULATION_HISTORY.DISPOSE_DETAIL，以容纳 WLT 多片按片处置详情
ALTER TABLE "FT_OWEN"."CIRCULATION_HISTORY" MODIFY ("DISPOSE_DETAIL" VARCHAR2(4000));

COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY.DISPOSE_DETAIL IS '规则化处置详情（如 DG:/RT:/W:，最长4000）';
