-- FT_OWEN.FT_CLIENT_ERROR：客户端未捕获异常 / Qt fatal 上报

CREATE SEQUENCE "FT_OWEN"."SEQ_FT_CLIENT_ERROR"
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  NOCYCLE;

CREATE TABLE "FT_OWEN"."FT_CLIENT_ERROR"
   (	"ID" NUMBER(38,0) DEFAULT FT_OWEN.SEQ_FT_CLIENT_ERROR.NEXTVAL NOT NULL ENABLE,
	"REPORT_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
	"OCCURRED_AT" TIMESTAMP,
	"RECEIVED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP,
	"EVENT_TYPE" VARCHAR2(32 CHAR),
	"EXCEPTION_TYPE" VARCHAR2(256 CHAR),
	"MESSAGE" VARCHAR2(1024 CHAR),
	"STACK_TRACE" CLOB,
	"HOSTNAME" VARCHAR2(128 CHAR),
	"OS_USER" VARCHAR2(64 CHAR),
	"EMPLOYEE_NO" VARCHAR2(20 CHAR),
	"USER_ID" NUMBER(38,0),
	"APP_MODE" VARCHAR2(16 CHAR),
	"FROZEN" NUMBER(1,0) DEFAULT 0,
	"CLIENT_IP" VARCHAR2(64 CHAR),
	 CONSTRAINT "FT_CLIENT_ERROR_PK" PRIMARY KEY ("ID")
  USING INDEX TABLESPACE "FT_OWEN" ENABLE,
	 CONSTRAINT "UK_FT_CLIENT_ERROR_REPORT_ID" UNIQUE ("REPORT_ID")
  USING INDEX TABLESPACE "FT_OWEN" ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "FT_OWEN" ;

CREATE INDEX "FT_OWEN"."IDX_FT_CLIENT_ERROR_OCCURRED"
  ON "FT_OWEN"."FT_CLIENT_ERROR" ("OCCURRED_AT")
  TABLESPACE "FT_OWEN";

CREATE INDEX "FT_OWEN"."IDX_FT_CLIENT_ERROR_EMP"
  ON "FT_OWEN"."FT_CLIENT_ERROR" ("EMPLOYEE_NO")
  TABLESPACE "FT_OWEN";

COMMENT ON TABLE FT_OWEN.FT_CLIENT_ERROR IS 'Hold 处置客户端未捕获异常 / Qt fatal';
COMMENT ON COLUMN FT_OWEN.FT_CLIENT_ERROR.REPORT_ID IS '客户端 UUID，幂等去重';
COMMENT ON COLUMN FT_OWEN.FT_CLIENT_ERROR.EVENT_TYPE IS 'UNCAUGHT / THREAD_UNCAUGHT / QT_FATAL';
COMMENT ON COLUMN FT_OWEN.FT_CLIENT_ERROR.FROZEN IS '1=PyInstaller 冻结进程 0=源码启动';
