-- FT_OWEN.HISTORY_DISPOSITION 定义

CREATE TABLE "FT_OWEN"."HISTORY_DISPOSITION" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PRO_ENG_ID" NUMBER NOT NULL ENABLE, 
	"WAFER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"DISPOSE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"ENG_DISPOSE" NUMBER NOT NULL ENABLE, 
	"DISPOSE_COMMENT" VARCHAR2(512), 
	"DISPOSE_START" DATE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FT_OWEN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FT_OWEN" ;


-- FT_OWEN.HISTORY_DISPOSITION 外键

ALTER TABLE "FT_OWEN"."HISTORY_DISPOSITION" ADD CONSTRAINT "HISTORY_DISPOSITON_FK" FOREIGN KEY ("PRO_ENG_ID")
	  REFERENCES "FT_OWEN"."USERS" ("ID") ENABLE;