-- FT_OWEN.FT_ENG_NOTES 定义

CREATE SEQUENCE "FT_OWEN"."SEQ_FT_ENG_NOTES"
  MINVALUE 1
  MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOORDER
  NOCYCLE;

CREATE TABLE "FT_OWEN"."FT_ENG_NOTES" 
   (	"ID" NUMBER(38,0) DEFAULT FT_OWEN.SEQ_FT_ENG_NOTES.NEXTVAL NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(38,0), 
	"NOTE" VARCHAR2(500), 
	"IS_AVAILABLE" NUMBER(38,0) DEFAULT 1, 
	"TYPE" VARCHAR2(100), 
	 CONSTRAINT "FT_ENG_NOTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FT_OWEN"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "FT_OWEN" ;

COMMENT ON COLUMN FT_OWEN.FT_ENG_NOTES.IS_AVAILABLE IS '0:不可用
1:可用';
COMMENT ON COLUMN FT_OWEN.FT_ENG_NOTES."TYPE" IS 'MES: 自动同步来的
MANUL:手动添加的';
