-- FT_OWEN.FT_HOLD_INFO_TEST 定义

CREATE TABLE "FT_OWEN"."FT_HOLD_INFO_TEST" 
   (	"ID" NUMBER DEFAULT FT_OWEN.SEQ_FT_HOLD_INFO_TEST.NEXTVAL NOT NULL ENABLE, 
	"HOLD_DTTM" VARCHAR2(30) NOT NULL ENABLE, 
	"STATION" VARCHAR2(20) NOT NULL ENABLE, 
	"EQUIP_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"PRODUCT_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LOT_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"WAFER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"HOLD_CODE" VARCHAR2(10) NOT NULL ENABLE, 
	"HOLD_REASON" VARCHAR2(512) NOT NULL ENABLE, 
	"SOURCE" NUMBER DEFAULT 0, 
	"SECOND_CODE" VARCHAR2(50), 
	"ROUTE_ID" VARCHAR2(50), 
	"GRADE_NUM" VARCHAR2(512), 
	"HOLD_RECORD_ID" NUMBER(38,0) DEFAULT 0, 
	"HOLDING" NUMBER(1,0) DEFAULT 0, 
	"REMARK" VARCHAR2(512), 
	 CONSTRAINT "FT_HOLD_INFO_TEST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FT_OWEN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FT_OWEN" ;

CREATE INDEX "FT_OWEN"."FT_HOLD_INFO_TEST_WAFER_ID_IDX" ON "FT_OWEN"."FT_HOLD_INFO_TEST" ("WAFER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FT_OWEN" ;

-- 自动关闭 / 在线 hold 关联：按 HOLD_RECORD_ID + HOLDING 查找
CREATE INDEX "FT_OWEN"."FT_HOLD_INFO_TEST_REC_HOLDING_IDX"
  ON "FT_OWEN"."FT_HOLD_INFO_TEST" ("HOLD_RECORD_ID", "HOLDING")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "FT_OWEN";

-- 正式表同名索引（若使用 FT_HOLD_INFO）：
-- CREATE INDEX "FT_OWEN"."FT_HOLD_INFO_REC_HOLDING_IDX"
--   ON "FT_OWEN"."FT_HOLD_INFO" ("HOLD_RECORD_ID", "HOLDING")
--   TABLESPACE "FT_OWEN";
