-- FT_OWEN.FT_HOLD_PREDICT：FT 可放行概率静默打分

CREATE SEQUENCE FT_OWEN.FT_HOLD_PREDICT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE FT_OWEN.FT_HOLD_PREDICT (
    ID NUMBER(38,0) DEFAULT FT_OWEN.FT_HOLD_PREDICT_SEQ.NEXTVAL NOT NULL,
    HOLD_RECORD_ID NUMBER(38,0) NOT NULL,
    MODEL_VERSION VARCHAR2(64) NOT NULL,
    FEATURE_VERSION VARCHAR2(32) NOT NULL,
    P_RELEASE NUMBER(8,6),
    BYSITE_INDEX NUMBER(8,6),
    ROUTE_IS_ENG NUMBER(1),
    MISSING_BYSITE NUMBER(1) DEFAULT 1 NOT NULL,
    MISSING_TEST_WAFER NUMBER(1) DEFAULT 1 NOT NULL,
    FEATURES_JSON CLOB,
    PREDICTED_AT DATE DEFAULT SYSDATE NOT NULL,
    LABEL_DISPOSE NUMBER(38,0),
    LABEL_Y NUMBER(1),
    LABELED_AT DATE,
    CONSTRAINT FT_HOLD_PREDICT_PK PRIMARY KEY (ID),
    CONSTRAINT FT_HOLD_PREDICT_REC_MDL_UK UNIQUE (HOLD_RECORD_ID, MODEL_VERSION),
    CONSTRAINT FT_HOLD_PREDICT_RECORD_FK FOREIGN KEY (HOLD_RECORD_ID)
        REFERENCES FT_OWEN.FT_HOLD_RECORD (ID) ON DELETE CASCADE
);

CREATE INDEX FT_OWEN.FT_HOLD_PREDICT_LABEL_IDX
    ON FT_OWEN.FT_HOLD_PREDICT (LABEL_Y, MODEL_VERSION);

COMMENT ON TABLE FT_OWEN.FT_HOLD_PREDICT IS 'FT 可放行概率静默预测；不参与处置决策';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_PREDICT.P_RELEASE IS '校准后的可放行概率 [0,1]；无模型时为空';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_PREDICT.BYSITE_INDEX IS 'site 误测综合指数，越高越像少数 site 误测';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_PREDICT.ROUTE_IS_ENG IS 'ROUTE_ID 含 ENG 则为 1';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_PREDICT.FEATURES_JSON IS '打分当时的完整特征快照';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_PREDICT.LABEL_DISPOSE IS '工程师首次意见 1/2/3/5，回填后才有';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_PREDICT.LABEL_Y IS '1=放行 0=非放行';
