-- 测试环境：FT_HOLD_RECORD_TEST / CIRCULATION_HISTORY_TEST
-- debug 模式使用本文件中的表；release 仍用 FT_HOLD_RECORD / CIRCULATION_HISTORY

CREATE SEQUENCE FT_OWEN.FT_HOLD_RECORD_TEST_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE FT_OWEN.SEQ_CIRCULATION_TEST
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE FT_OWEN.FT_HOLD_RECORD_TEST (
    ID NUMBER(38,0) DEFAULT FT_OWEN.FT_HOLD_RECORD_TEST_SEQ.NEXTVAL NOT NULL ENABLE,
    PRODUCT_ID VARCHAR2(20) NOT NULL ENABLE,
    STATION VARCHAR2(20) NOT NULL ENABLE,
    EQUIP_ID VARCHAR2(20) NOT NULL ENABLE,
    LOT_ID VARCHAR2(20) NOT NULL ENABLE,
    WAFER_ID VARCHAR2(100) NOT NULL ENABLE,
    HOLD_CODE VARCHAR2(100),
    HOLD_REASON VARCHAR2(512),
    SOURCE NUMBER(38,0) NOT NULL ENABLE,
    SECOND_CODE VARCHAR2(50),
    ROUTE_ID VARCHAR2(50),
    GRADE_NUM VARCHAR2(512),
    RECORD_TYPE NUMBER(38,0) NOT NULL ENABLE,
    STATUS NUMBER(38,0) NOT NULL ENABLE,
    LAST_CIRCULATION_ID NUMBER(38,0),
    HOLD_DTTM DATE,
    HOLD_WAFER_ATTR NUMBER(38,0) DEFAULT 0,
    CONSTRAINT FT_HOLD_RECORD_TEST_PK PRIMARY KEY (ID)
);

CREATE INDEX FT_OWEN.FT_HOLD_RECORD_TEST_ST_IDX
    ON FT_OWEN.FT_HOLD_RECORD_TEST (STATUS);

COMMENT ON TABLE FT_OWEN.FT_HOLD_RECORD_TEST IS 'Hold 处置单（测试环境）';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD_TEST.SOURCE IS '0: MES 1: 手提';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD_TEST.ANNEX_FTP_PATH IS '附件FTP路径；多图以@引导拼接';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD_TEST.RECORD_TYPE IS 'HOLD类型，对应处置单type';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD_TEST.STATUS IS '状态';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD_TEST.LAST_CIRCULATION_ID IS '最新流转记录的ID';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD_TEST.HOLD_WAFER_ATTR IS '片属性比特位（十进制）：1真空包 2梓一合批 4 IQC_ATE合批 8 ATE合批 16 FVI合批；可 OR';

CREATE TABLE FT_OWEN.CIRCULATION_HISTORY_TEST (
    ID NUMBER(38,0) DEFAULT FT_OWEN.SEQ_CIRCULATION_TEST.NEXTVAL,
    HOLD_RECORD_ID NUMBER(38,0) NOT NULL ENABLE,
    DISPOSED_OWNER_ID NUMBER(38,0) DEFAULT 1 NOT NULL ENABLE,
    DISPOSE NUMBER(38,0) DEFAULT 0,
    NEXT_OWNER_ID NUMBER(38,0),
    DISPOSE_SOURCE VARCHAR2(100),
    DISPOSE_DTTM DATE,
    DISPOSE_TYPE NUMBER(38,0),
    DISPOSE_DETAIL VARCHAR2(4000),
    DISPOSE_NOTE VARCHAR2(1024),
    DISPOSE_MANUAL_NOTE VARCHAR2(1024),
    CONSTRAINT PK_CIRCULATION_HIST_TEST PRIMARY KEY (ID)
);

COMMENT ON TABLE FT_OWEN.CIRCULATION_HISTORY_TEST IS '处置单流转记录（测试环境）';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY_TEST.DISPOSED_OWNER_ID IS '默认1(root)代表是系统生成';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY_TEST.DISPOSE_SOURCE IS '处置信息来源, SYS or JDY';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY_TEST.DISPOSE_TYPE IS '创建、放行、降级、重测、可靠性分析、关闭、转交、回退';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY_TEST.DISPOSE_DETAIL IS '规则化处置详情（如 DG:/RT:/W:，最长4000）';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY_TEST.DISPOSE_NOTE IS '工程备注';
COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY_TEST.DISPOSE_MANUAL_NOTE IS '手输备注（工程师/生产任意处置可选，最长1024）';

ALTER TABLE FT_OWEN.CIRCULATION_HISTORY_TEST
    ADD CONSTRAINT CIRC_HIST_TEST_REC_FK FOREIGN KEY (HOLD_RECORD_ID)
    REFERENCES FT_OWEN.FT_HOLD_RECORD_TEST (ID) ON DELETE CASCADE ENABLE;

ALTER TABLE FT_OWEN.CIRCULATION_HISTORY_TEST
    ADD CONSTRAINT CIRC_HIST_TEST_USERS_FK FOREIGN KEY (DISPOSED_OWNER_ID)
    REFERENCES FT_OWEN.USERS (ID) ENABLE;

-- 预测表 FK 指向 hold_record；debug 必须用测试表，否则会写到正式 FT_HOLD_PREDICT
CREATE SEQUENCE FT_OWEN.FT_HOLD_PREDICT_TEST_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE FT_OWEN.FT_HOLD_PREDICT_TEST (
    ID NUMBER(38,0) DEFAULT FT_OWEN.FT_HOLD_PREDICT_TEST_SEQ.NEXTVAL NOT NULL,
    HOLD_RECORD_ID NUMBER(38,0) NOT NULL,
    MODEL_VERSION VARCHAR2(64) NOT NULL,
    FEATURE_VERSION VARCHAR2(32) NOT NULL,
    P_RELEASE NUMBER(8,6),
    BYSITE_INDEX NUMBER(8,6),
    ROUTE_IS_ENG NUMBER(1),
    MISSING_BYSITE NUMBER(1) DEFAULT 1 NOT NULL,
    MISSING_TEST_WAFER NUMBER(1) DEFAULT 1 NOT NULL,
    FEATURES_JSON CLOB,
    PREDICTED_AT DATE DEFAULT SYSDATE NOT NULL,
    LABEL_DISPOSE NUMBER(38,0),
    LABEL_Y NUMBER(1),
    LABELED_AT DATE,
    CONSTRAINT FT_HOLD_PREDICT_TEST_PK PRIMARY KEY (ID),
    CONSTRAINT FT_HOLD_PREDICT_TEST_UK UNIQUE (HOLD_RECORD_ID, MODEL_VERSION),
    CONSTRAINT FT_HOLD_PREDICT_TEST_FK FOREIGN KEY (HOLD_RECORD_ID)
        REFERENCES FT_OWEN.FT_HOLD_RECORD_TEST (ID) ON DELETE CASCADE
);

CREATE INDEX FT_OWEN.FT_HOLD_PREDICT_TEST_LBL_IDX
    ON FT_OWEN.FT_HOLD_PREDICT_TEST (LABEL_Y, MODEL_VERSION);

COMMENT ON TABLE FT_OWEN.FT_HOLD_PREDICT_TEST IS 'FT 可放行概率静默预测（测试环境）';
