-- FT_OWEN.FT_HOLD_RECORD 定义

CREATE TABLE "FT_OWEN"."FT_HOLD_RECORD" 
   (	"ID" NUMBER(38,0) DEFAULT FT_OWEN.FT_HOLD_RECORD_SEQ.NEXTVAL NOT NULL ENABLE, 
	"PRODUCT_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"STATION" VARCHAR2(20) NOT NULL ENABLE, 
	"EQUIP_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"LOT_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"WAFER_ID" VARCHAR2(100) NOT NULL ENABLE, 
	"HOLD_CODE" VARCHAR2(100), 
	"HOLD_REASON" VARCHAR2(512), 
	"SOURCE" NUMBER(38,0) NOT NULL ENABLE, 
	"SECOND_CODE" VARCHAR2(50), 
	"ROUTE_ID" VARCHAR2(50), 
	"GRADE_NUM" VARCHAR2(512), 
	"RECORD_TYPE" NUMBER(38,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(38,0) NOT NULL ENABLE, 
	"LAST_CIRCULATION_ID" NUMBER(38,0), 
	"HOLD_DTTM" DATE, 
	"HOLD_WAFER_ATTR" NUMBER(38,0) DEFAULT 0, 
	 CONSTRAINT "FT_HOLD_RECORD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FT_OWEN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FT_OWEN" ;

CREATE INDEX "FT_OWEN"."FT_HOLD_RECORD_STATUS_IDX" ON "FT_OWEN"."FT_HOLD_RECORD" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FT_OWEN" ;

COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD."SOURCE" IS '0: MES
1: 手提';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD.RECORD_TYPE IS 'HOLD类型，对应处置单type';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD.STATUS IS '状态';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD.LAST_CIRCULATION_ID IS '最新流转记录的ID';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD.ANNEX_FTP_PATH IS '附件FTP路径；多图以@引导拼接，如 @/a.jpg@/b.jpg';
COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD.HOLD_WAFER_ATTR IS '片属性比特位（十进制）：1真空包 2梓一合批 4 IQC_ATE合批 8 ATE合批 16 FVI合批；可 OR';