-- FT_OWEN.HOLD_INFO 定义

CREATE TABLE "FT_OWEN"."HOLD_INFO" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"WAFER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"PRODUCT_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"EQUIP_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"HOLD_DATETIME" VARCHAR2(30) NOT NULL ENABLE, 
	"HOLD_REASON" VARCHAR2(512) NOT NULL ENABLE, 
	"NOTICE_FLAG" NUMBER(3,0) NOT NULL ENABLE, 
	"STATUS_CODE" NUMBER(11,0) NOT NULL ENABLE, 
	"JDY_STATUS_FLAG" NUMBER(11,0) NOT NULL ENABLE, 
	"DISPOSE" NUMBER(11,0) DEFAULT NULL, 
	"SECOND_CODE" VARCHAR2(20) DEFAULT NULL, 
	"ROUTE_ID" VARCHAR2(20) DEFAULT NULL, 
	"GRADE_NUM" VARCHAR2(512) DEFAULT NULL, 
	"SURVEYOR" VARCHAR2(20) DEFAULT NULL, 
	"DISPOSE_COMMENT" VARCHAR2(512) DEFAULT NULL, 
	"DATA_FLAG" NUMBER(3,0) DEFAULT 0, 
	 CONSTRAINT "PK_HOLD_INFO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FT_OWEN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FT_OWEN" ;