-- USERS 增加强制改密标记。debug / release 共用 FT_OWEN.USERS，执行一次即可。
-- 上线顺序：先执行本 DDL，再部署带 MUST_CHANGE_PWD 字段的后端。

ALTER TABLE FT_OWEN.USERS ADD MUST_CHANGE_PWD NUMBER(1);

UPDATE FT_OWEN.USERS SET MUST_CHANGE_PWD = 1;

ALTER TABLE FT_OWEN.USERS MODIFY MUST_CHANGE_PWD NUMBER(1) DEFAULT 1 NOT NULL;

COMMENT ON COLUMN FT_OWEN.USERS.MUST_CHANGE_PWD IS '1=下次登录须在 Web 改密；0=已改过';
