-- 新增 CIRCULATION_HISTORY.DISPOSE_MANUAL_NOTE：任意处置可选手输备注
ALTER TABLE "FT_OWEN"."CIRCULATION_HISTORY" ADD ("DISPOSE_MANUAL_NOTE" VARCHAR2(1024));

COMMENT ON COLUMN FT_OWEN.CIRCULATION_HISTORY.DISPOSE_MANUAL_NOTE IS '手输备注（工程师/生产任意处置可选，最长1024）';
