-- FT_HOLD_RECORD / FT_HOLD_RECORD_TEST 增加 HOLD_WAFER_ATTR（比特位属性，十进制存储）
-- bit0=1 真空包；bit1=2 梓一合批；bit2=4 IQC_ATE合批；bit3=8 ATE合批；bit4=16 FVI合批

ALTER TABLE FT_OWEN.FT_HOLD_RECORD ADD (
    HOLD_WAFER_ATTR NUMBER(38,0) DEFAULT 0
);

COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD.HOLD_WAFER_ATTR IS
'片属性比特位（十进制）：1真空包 2梓一合批 4 IQC_ATE合批 8 ATE合批 16 FVI合批；可 OR';

ALTER TABLE FT_OWEN.FT_HOLD_RECORD_TEST ADD (
    HOLD_WAFER_ATTR NUMBER(38,0) DEFAULT 0
);

COMMENT ON COLUMN FT_OWEN.FT_HOLD_RECORD_TEST.HOLD_WAFER_ATTR IS
'片属性比特位（十进制）：1真空包 2梓一合批 4 IQC_ATE合批 8 ATE合批 16 FVI合批；可 OR';
